private _loadout = [];
//////////////////////////////////////////////////

_loadout = [["rhs_weap_m4a1_carryhandle","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15_bk","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip1"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["acu_jacket_uniform",[["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_packingBandage",6],["ACE_quikclot",4],["ACE_EarPlugs",1],["ACE_epinephrine",2],["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ItemcTabHCam",1],["ACE_morphine",2],["ACE_MapTools",1],["ACE_splint",4],["ACE_tourniquet",4],["rhsusf_mag_15Rnd_9x19_FMJ",1,15]]],["tft8_ciras_ocp_556",[["rhsusf_ANPVS_15",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_Flashlight_XL50",1],["rhsusf_acc_nt4_black",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30],["HandGrenade",2,1]]],[],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["01 Rifleman", _loadout] call ace_arsenal_fnc_addDefaultLoadout;

_loadout = [["rhs_weap_m249_pip","","","rhsusf_acc_ELCAN",["rhsusf_200rnd_556x45_mixed_box",200],[],"rhsusf_acc_saw_bipod"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["acu_jacket_uniform",[["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_packingBandage",6],["ACE_quikclot",4],["ACE_CableTie",2],["ACE_EarPlugs",1],["ACE_epinephrine",2],["ItemcTabHCam",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",4],["ACE_tourniquet",4],["rhsusf_mag_15Rnd_9x19_FMJ",1,15]]],["tft8_ciras_ocp_556",[["rhsusf_ANPVS_15",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_Flashlight_XL50",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhsusf_200rnd_556x45_mixed_box",2,200],["HandGrenade",2,1]]],["tft8_assaultpack_ocp",[["ACE_SpareBarrel",1,1],["rhsusf_200rnd_556x45_mixed_box",2,200]]],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["02 Auto Rifleman", _loadout] call ace_arsenal_fnc_addDefaultLoadout;

_loadout = [["rhs_weap_m16a4","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15_bk","optic_AMS",["SMA_30Rnd_556x45_Mk262",30],[],"CUP_bipod_Harris_1A2_L_BLK"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["acu_jacket_uniform",[["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_packingBandage",6],["ACE_quikclot",4],["ACE_CableTie",2],["ACE_EarPlugs",1],["ACE_epinephrine",2],["ItemcTabHCam",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_RangeCard",1],["ACE_splint",4],["ACE_tourniquet",4],["rhsusf_mag_15Rnd_9x19_FMJ",1,15]]],["tft8_ciras_ocp_556",[["rhsusf_ANPVS_15",2],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_Flashlight_XL50",1],["rhsusf_acc_premier_anpvs27",1],["CUP_muzzle_snds_M16",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["SMA_30Rnd_556x45_Mk262",7,30],["HandGrenade",2,1]]],[],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["03 Marksman", _loadout] call ace_arsenal_fnc_addDefaultLoadout;

_loadout = [["rhs_weap_m4_carryhandle_m203S","rhsusf_acc_SF3P556","CUP_acc_ANPEQ_15_Flashlight_Black_L","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["acu_jacket_uniform",[["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_packingBandage",6],["ACE_quikclot",4],["ACE_CableTie",2],["ACE_EarPlugs",1],["ACE_epinephrine",2],["ItemcTabHCam",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_tourniquet",4],["ACE_splint",4],["rhsusf_mag_15Rnd_9x19_FMJ",1,15]]],["tft8_ciras_ocp_556",[["rhsusf_ANPVS_15",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_Flashlight_XL50",1],["rhsusf_acc_nt4_black",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["HandGrenade",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30]]],["tft8_assaultpack_ocp",[["1Rnd_HE_Grenade_shell",8,1],["UGL_FlareCIR_F",2,1],["UGL_FlareWhite_F",2,1],["1Rnd_SmokeRed_Grenade_shell",3,1],["1Rnd_Smoke_Grenade_shell",4,1]]],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["04 Grenadier", _loadout] call ace_arsenal_fnc_addDefaultLoadout;

_loadout = [["rhs_weap_m4a1_carryhandle","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15_bk","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip1"],["launch_MRAWS_green_F","","","",["MRAWS_HEAT_F",1],[],""],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["acu_jacket_uniform",[["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_packingBandage",6],["ACE_quikclot",4],["ACE_CableTie",2],["ACE_EarPlugs",1],["ACE_epinephrine",2],["ItemcTabHCam",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",4],["ACE_tourniquet",4],["rhsusf_mag_15Rnd_9x19_FMJ",1,15]]],["tft8_ciras_ocp_556",[["rhsusf_ANPVS_15",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_Flashlight_XL50",1],["rhsusf_acc_nt4_black",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30],["HandGrenade",2,1]]],["tft8_kitbag_ocp",[["MRAWS_HEAT_F",3,1],["MRAWS_HE_F",4,1]]],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["05 Anti-Tank", _loadout] call ace_arsenal_fnc_addDefaultLoadout;

_loadout = [["rhs_weap_m4a1_carryhandle","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15_bk","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip1"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["acu_jacket_uniform",[["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_packingBandage",6],["ACE_quikclot",4],["ACE_CableTie",2],["ACE_EarPlugs",1],["ACE_epinephrine",2],["ItemcTabHCam",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",4],["ACE_tourniquet",4],["rhsusf_mag_15Rnd_9x19_FMJ",1,15]]],["tft8_ciras_ocp_556",[["rhsusf_ANPVS_15",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_Flashlight_XL50",1],["rhsusf_acc_nt4_black",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30],["HandGrenade",2,1]]],["tft8_assaultpack_ocp",[["ACE_elasticBandage",12],["ACE_packingBandage",12],["ACE_fieldDressing",8],["ACE_quikclot",8],["ACE_epinephrine",6],["ACE_tourniquet",6],["ACE_morphine",6],["ACE_salineIV_500",4],["ACE_surgicalKit",1],["ACE_adenosine",3]]],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["06 Combat Life Saver", _loadout] call ace_arsenal_fnc_addDefaultLoadout;

_loadout = [["rhs_weap_m240B","hlc_muzzle_MAG58_Brake","","rhsusf_acc_compm4",["150Rnd_762x51_Box_Tracer",150],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["acu_jacket_uniform",[["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_packingBandage",6],["ACE_quikclot",4],["ACE_EarPlugs",1],["ACE_epinephrine",2],["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ItemcTabHCam",1],["ACE_morphine",2],["ACE_MapTools",1],["ACE_splint",4],["ACE_tourniquet",4],["rhsusf_mag_15Rnd_9x19_FMJ",1,15]]],["tft8_ciras_ocp_556",[["rhsusf_ANPVS_15",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_Flashlight_XL50",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["HandGrenade",2,1],["rhsusf_mag_15Rnd_9x19_JHP",2,15]]],["tft8_assaultpack_ocp",[["150Rnd_762x51_Box_Tracer",3,150]]],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["07 Machinegunner", _loadout] call ace_arsenal_fnc_addDefaultLoadout;

_loadout = [["rhs_weap_m4a1_carryhandle","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15_bk","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip1"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["acu_jacket_uniform",[["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_packingBandage",6],["ACE_quikclot",4],["ACE_EarPlugs",1],["ACE_epinephrine",2],["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ItemcTabHCam",1],["ACE_morphine",2],["ACE_MapTools",1],["ACE_splint",4],["ACE_tourniquet",4],["rhsusf_mag_15Rnd_9x19_FMJ",1,15]]],["tft8_ciras_ocp_556",[["rhsusf_ANPVS_15",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_Flashlight_XL50",1],["rhsusf_acc_nt4_black",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30],["HandGrenade",2,1]]],["tft8_kitbag_ocp",[["150Rnd_762x51_Box_Tracer",6,150]]],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["08 Asst. Machinegunner", _loadout] call ace_arsenal_fnc_addDefaultLoadout;

_loadout = [["rhs_weap_m4a1_carryhandle","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15_bk","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip1"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["acu_jacket_uniform",[["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_packingBandage",6],["ACE_quikclot",4],["ACE_EarPlugs",1],["ACE_epinephrine",2],["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ItemcTabHCam",1],["ACE_morphine",2],["ACE_MapTools",1],["ACE_splint",4],["ACE_tourniquet",4],["rhsusf_mag_15Rnd_9x19_FMJ",1,15]]],["tft8_ciras_ocp_556",[["rhsusf_ANPVS_15",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_Flashlight_XL50",1],["rhsusf_acc_nt4_black",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30],["HandGrenade",2,1]]],["tft8_onebag_mk6",[]],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["09 Mortar Gunner", _loadout] call ace_arsenal_fnc_addDefaultLoadout;

_loadout = [["rhs_weap_m4a1_carryhandle","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15_bk","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip1"],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["acu_jacket_uniform",[["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_packingBandage",6],["ACE_quikclot",4],["ACE_EarPlugs",1],["ACE_epinephrine",2],["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ItemcTabHCam",1],["ACE_morphine",2],["ACE_MapTools",1],["ACE_splint",4],["ACE_tourniquet",4],["rhsusf_mag_15Rnd_9x19_FMJ",1,15]]],["tft8_ciras_ocp_556",[["rhsusf_ANPVS_15",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_Flashlight_XL50",1],["rhsusf_acc_nt4_black",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_M855A1_PMAG",7,30],["HandGrenade",2,1]]],["tft8_kitbag_ocp",[["ACE_1Rnd_82mm_Mo_HE",7,1]]],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["Binocular","","","",[],[],""],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["10 Mortar Loader", _loadout] call ace_arsenal_fnc_addDefaultLoadout;

_loadout = [["rhs_weap_m4a1","","","rhsusf_acc_compm4",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],["rhsusf_weap_m9","","","",["rhsusf_mag_15Rnd_9x19_FMJ",15],[],""],["acu_jacket_uniform",[["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_quikclot",4],["ACE_packingBandage",6],["ACE_CableTie",2],["ACE_EarPlugs",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_splint",4],["ACE_tourniquet",4],["ItemAndroid",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",1,30]]],["tft8_helipilot_vest",[["rhsusf_ANPVS_15",1],["Chemlight_blue",2,1],["Chemlight_red",1,1],["Chemlight_green",1,1],["SmokeShell",2,1],["SmokeShellBlue",1,1],["ACE_HandFlare_White",1,1],["rhsusf_mag_15Rnd_9x19_FMJ",2,15],["rhs_mag_30Rnd_556x45_M855A1_PMAG",4,30]]],["tft8_rt1523g_ocp",[]],"rhsusf_hgu56p_visor_mask_green","",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["11 Aircrew", _loadout] call ace_arsenal_fnc_addDefaultLoadout;

_loadout = [[],[],[],["acu_jacket_uniform",[["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_packingBandage",6],["ACE_quikclot",4],["ACE_CableTie",2],["ACE_EarPlugs",1],["ACE_epinephrine",2],["ItemcTabHCam",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_splint",4],["ACE_tourniquet",4]]],["tft8_ciras_ocp_556",[["rhsusf_ANPVS_15",1],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_SpraypaintGreen",1],["ACE_Flashlight_XL50",1],["SmokeShell",2,1],["SmokeShellGreen",2,1],["HandGrenade",2,1]]],[],"tft8_ach_helmet_ocp","rhsusf_oakley_goggles_clr",["Binocular","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["12 Basic Rifleman Kit", _loadout] call ace_arsenal_fnc_addDefaultLoadout;

_loadout = [[],[],[],["acu_jacket_uniform",[["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_MapTools",1],["ACE_packingBandage",6],["ACE_quikclot",4],["ACE_elasticBandage",6],["ACE_fieldDressing",4],["ACE_epinephrine",2],["ACE_EarPlugs",1],["ACE_CableTie",2],["ItemcTabHCam",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1]]],["tft8_helipilot_vest",[["Patrol_capv2_ocp",1],["rhsusf_ANPVS_15",1],["Chemlight_blue",2,1],["Chemlight_red",1,1],["Chemlight_green",1,1],["ACE_HandFlare_White",1,1],["SmokeShell",2,1],["SmokeShellBlue",1,1]]],["tft8_rt1523g_ocp",[]],"rhsusf_hgu56p_visor_mask_green","",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","ItemWatch",""]];
["13 Basic Aviation Kit", _loadout] call ace_arsenal_fnc_addDefaultLoadout;

_loadout = [[],[],[],["acu_jacket_uniform",[["ACE_fieldDressing",4],["ACE_elasticBandage",6],["ACE_quikclot",4],["ACE_packingBandage",6],["ACE_CableTie",2],["ACE_EarPlugs",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_splint",4],["ACE_tourniquet",4]]],[],[],"Patrol_cap_ocp","",[],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""]] ;
["14 Parade", _loadout] call ace_arsenal_fnc_addDefaultLoadout;

/*

_loadout = REPLACEMEloadout_code ;
["10 REPLACEMEloadout_name", _loadout] call ace_arsenal_fnc_addDefaultLoadout;

*/