//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 198.146373 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class TFT_TA {
        displayName = "Talon Aegis";
        side = 0;
        flag = "x\cfp\addons\flags\Others\3percenters.paa";
        icon = "x\cfp\addons\flags\Others\3percenters.paa";
        priority = 0;
    };
};